import { SectionConfig, sameOpts, opts } from "./types";
import {
  INDUSTRY_OPTIONS,
  COUNTRY_OPTIONS,
  statesForCountries,
  contactPersonasForIndustry,
} from "./industry-options";

const EMPLOYEE_RANGES = sameOpts([
  "1–10", "11–25", "26–50", "51–100", "101–250", "251–500", "501–1,000", "1,001–5,000", "5,000+", "Any size",
]);

const REVENUE_RANGES = sameOpts([
  "Under $100K", "$100K–$500K", "$500K–$1M", "$1M–$5M", "$5M–$10M", "$10M–$50M", "$50M–$100M", "$100M+",
]);

const PRICE_RANGES = sameOpts([
  "Under $500", "$500–$1,000", "$1,000–$5,000", "$5,000–$10,000", "$10,000–$50,000", "$50,000+",
]);

export const LEAD_GEN_SCHEMA: SectionConfig[] = [
  {
    id: "your_business",
    title: "Your Business",
    intro: "A few basics so the AI understands what you sell and to whom.",
    fields: [
      {
        id: "business_name",
        label: "Business name",
        help: "What is your company or brand called?",
        example: "Acme Fitness",
        type: "text",
        required: true,
      },
      {
        id: "website",
        label: "Website",
        help: "Add your business website so the AI can understand your company better.",
        example: "https://www.infomist.com",
        type: "url",
        required: true,
      },
      {
        id: "what_you_sell",
        label: "What do you sell?",
        help: "Tell us what product or service you want to sell to new customers.",
        example: "AI automation services, accounting software, commercial real estate…",
        type: "textarea",
        required: true,
      },
      {
        id: "business_type",
        label: "Who do you sell to?",
        help: "Who normally pays you?",
        type: "select",
        options: opts([
          ["b2b", "Businesses (B2B)"],
          ["b2c", "Individuals (B2C)"],
          ["both", "Both"],
        ]),
        required: true,
      },
      {
        id: "business_category",
        label: "Main business category",
        help: "Pick the category that best describes your own business.",
        type: "select",
        options: INDUSTRY_OPTIONS,
        allowCustom: true,
        required: true,
      },
      {
        id: "main_services",
        label: "Main service or product",
        help: "Select all products or services you want to find customers for.",
        example: "AI automation, web development, SEO, paid advertising, CRM software…",
        type: "tags",
        allowCustom: true,
      },
      {
        id: "main_offer",
        label: "Main offer",
        help: "What are you offering this customer?",
        example: "Free consultation, free demo, 20% discount, free trial, custom quote…",
        type: "text",
      },
      {
        id: "typical_price",
        label: "Typical deal value",
        help: "Approximate value of a normal customer deal.",
        type: "select",
        options: PRICE_RANGES,
        allowAI: true,
      },
    ],
  },
  {
    id: "target_companies",
    title: "Target Companies",
    intro: "Tell us what kind of companies you want us to find.",
    fields: [
      {
        id: "target_industries",
        label: "What type of businesses do you want?",
        help: "Choose the industries most likely to need your product or service. You can pick more than one.",
        type: "multiselect",
        options: INDUSTRY_OPTIONS,
        allowCustom: true,
        allowAI: true,
      },
      {
        id: "company_size",
        label: "Company size",
        help: "Choose the approximate number of people working at the company.",
        type: "select",
        options: EMPLOYEE_RANGES,
        allowCustom: true,
      },
      {
        id: "annual_revenue",
        label: "Annual revenue",
        help: "Approximate yearly company income.",
        type: "select",
        options: REVENUE_RANGES,
        allowAI: true,
      },
      {
        id: "company_age",
        label: "How old should the company be?",
        help: "New startups and established companies may need different solutions.",
        type: "select",
        options: sameOpts(["Less than 1 year", "1–3 years", "3–5 years", "5–10 years", "10–20 years", "20+ years", "Any age"]),
      },
      {
        id: "company_stage",
        label: "Company stage",
        help: "Choose the type of company you want to sell to.",
        type: "select",
        options: sameOpts(["Startup", "Small Business", "Growing Business", "Mid-Market", "Enterprise", "Any"]),
        allowAI: true,
      },
      {
        id: "num_locations",
        label: "Number of locations",
        help: "How many offices or branches should the company have? Leave as 'Any' if this doesn't matter.",
        type: "select",
        options: sameOpts(["1", "2–5", "6–10", "11–50", "50+", "Any"]),
      },
    ],
  },
  {
    id: "location",
    title: "Location",
    fields: [
      {
        id: "target_countries",
        label: "Target countries",
        help: "Which countries should we look for companies in?",
        type: "multiselect",
        options: COUNTRY_OPTIONS,
        allowCustom: true,
        required: true,
      },
      {
        id: "target_states",
        label: "Target state / region",
        help: "Narrow it down further, or leave empty to cover the whole country.",
        type: "multiselect",
        options: statesForCountries,
        showIf: (v) => Array.isArray(v.target_countries) && (v.target_countries as string[]).length > 0,
      },
      {
        id: "target_cities",
        label: "Target cities",
        help: "Leave empty if you want the whole country or region.",
        example: "New York, Los Angeles, London, Dubai…",
        type: "tags",
      },
      {
        id: "location_scope",
        label: "Where should the company be located?",
        help: "Some companies have one head office but branches elsewhere — tell us which locations count.",
        type: "select",
        options: opts([
          ["hq", "Company headquarters only"],
          ["any_office", "Any office location"],
          ["both", "Both"],
        ]),
      },
      {
        id: "excluded_locations",
        label: "Places to exclude",
        help: "Any countries, states, or cities you specifically don't want leads from.",
        example: "Do not find companies in India or Pakistan.",
        type: "tags",
      },
    ],
  },
  {
    id: "growth",
    title: "Company Growth",
    intro: "These signals help us find companies that are actively growing and more likely to buy.",
    fields: [
      {
        id: "growth_rate",
        label: "Should the company be growing?",
        help: "Fast-growing companies often have more budget and urgency to buy.",
        type: "select",
        options: sameOpts(["Fast-growing", "Moderately growing", "Stable", "Any"]),
        allowAI: true,
      },
      {
        id: "hiring_status",
        label: "Should they be hiring?",
        help: "Companies that are hiring are usually growing and investing in new tools.",
        type: "select",
        options: opts([
          ["actively", "Yes, actively hiring"],
          ["selected_depts", "Hiring only in selected departments"],
          ["no_preference", "No preference"],
        ]),
        allowAI: true,
      },
      {
        id: "hiring_departments",
        label: "Which departments should be hiring?",
        help: "Pick the departments that would signal a good time to reach out.",
        type: "multiselect",
        options: sameOpts(["Sales", "Marketing", "IT", "Engineering", "AI", "HR", "Finance", "Operations", "Product"]),
        allowCustom: true,
        showIf: (v) => v.hiring_status === "selected_depts",
      },
      {
        id: "recent_expansion",
        label: "Recent expansion",
        help: "Companies opening new locations or entering new markets often need new services.",
        type: "select",
        options: sameOpts(["Recently expanded", "Opening new locations", "Entering new markets", "No preference"]),
      },
      {
        id: "recent_activity",
        label: "Recent company activity",
        help: "Any recent news that suggests the company is a good time to contact.",
        type: "multiselect",
        options: sameOpts(["New product launch", "New office", "New leadership", "Funding", "Expansion", "Hiring"]),
        allowAI: true,
      },
    ],
  },
  {
    id: "funding",
    title: "Funding",
    intro: "Optional — skip this if funding doesn't matter for your product.",
    fields: [
      {
        id: "funding_status",
        label: "Funding status",
        help: "Some products are only useful for companies that have raised outside investment.",
        type: "select",
        options: sameOpts(["Bootstrapped", "Funded", "No preference"]),
      },
      {
        id: "funding_stage",
        label: "Funding stage",
        help: "How far along their fundraising should they be?",
        type: "select",
        options: sameOpts(["Pre-seed", "Seed", "Series A", "Series B", "Series C+", "Any"]),
        showIf: (v) => v.funding_status === "Funded",
      },
      {
        id: "recently_funded",
        label: "Recently funded?",
        help: "Companies that just raised money often have fresh budget to spend.",
        type: "select",
        options: sameOpts(["Last 3 months", "Last 6 months", "Last 12 months", "Any time", "No preference"]),
        showIf: (v) => v.funding_status === "Funded",
      },
    ],
  },
  {
    id: "contact",
    title: "Who Should We Contact?",
    intro: "Tell us which person at the company we should try to reach.",
    fields: [
      {
        id: "contact_titles",
        label: "Who should we contact?",
        help: "Pick the job titles most likely to make the buying decision.",
        type: "multiselect",
        options: contactPersonasForIndustry,
        allowCustom: true,
        required: true,
      },
      {
        id: "contact_department",
        label: "Department",
        help: "Which department does this person usually work in?",
        type: "select",
        options: sameOpts(["Management", "Sales", "Marketing", "IT", "Engineering", "HR", "Finance", "Operations", "Product", "Customer Success"]),
        allowCustom: true,
      },
    ],
  },
  {
    id: "perfect_lead",
    title: "What Makes A Perfect Lead",
    fields: [
      {
        id: "good_customer_description",
        label: "What makes someone a good customer?",
        help: "Describe your ideal customer in your own words — this helps the AI understand what to look for.",
        example: "A company with 50–500 employees that is growing quickly and needs AI automation.",
        type: "textarea",
        allowAI: true,
      },
      {
        id: "customer_problems",
        label: "What problem should they have?",
        help: "What is the customer struggling with that your product or service solves?",
        type: "multiselect",
        options: sameOpts(["Need more sales", "Need automation", "Need software", "Need employees", "Need marketing", "Outdated website", "High operating costs", "Need AI", "Need more customers"]),
        allowCustom: true,
      },
      {
        id: "exclude_lead_types",
        label: "Who should NOT be a lead?",
        help: "Any type of company or person we should skip entirely.",
        example: "Do not target freelancers, students or companies with fewer than 10 employees.",
        type: "tags",
      },
    ],
  },
  {
    id: "similar_customers",
    title: "Similar Customers",
    fields: [
      {
        id: "has_existing_customers",
        label: "Do you already have good customers?",
        help: "If you give us examples, AI can find more companies just like them.",
        type: "yesno",
      },
      {
        id: "example_customers",
        label: "Add example customer companies",
        help: "Give us companies you already consider good customers. AI can use them to find similar businesses.",
        example: "HubSpot, Salesforce, Monday.com",
        type: "tags",
        showIf: (v) => v.has_existing_customers === "yes",
      },
    ],
  },
  {
    id: "lead_output",
    title: "Lead Output",
    fields: [
      {
        id: "lead_count",
        label: "How many leads do you want?",
        help: "How many new leads should we try to find each time this runs?",
        type: "select",
        options: sameOpts(["25", "50", "100", "250", "500", "1,000"]),
        allowCustom: true,
        required: true,
      },
      {
        id: "lead_frequency",
        label: "How often?",
        help: "Should this run once, or keep finding new leads automatically?",
        type: "select",
        options: opts([
          ["one_time", "One time"],
          ["daily", "Daily"],
          ["weekly", "Weekly"],
          ["monthly", "Monthly"],
        ]),
        required: true,
      },
      {
        id: "lead_quality",
        label: "Minimum lead quality",
        help: "Stricter quality means fewer, better-matched leads. Looser means more leads, some less relevant.",
        type: "select",
        options: sameOpts(["Any relevant lead", "Good", "Very good", "Only high-quality leads"]),
        allowAI: true,
      },
      {
        id: "contact_details_needed",
        label: "What contact details do you need?",
        help: "Choose everything you'd like us to try to find for each lead.",
        type: "multiselect",
        options: sameOpts(["Verified email", "Phone", "LinkedIn", "Website", "Company details"]),
      },
    ],
  },
  {
    id: "outreach",
    title: "Outreach",
    fields: [
      {
        id: "outreach_channels",
        label: "How should we contact them?",
        help: "Which channel should we use to reach out to new leads?",
        type: "multiselect",
        options: sameOpts(["Email"]),
      },
      {
        id: "email_tone",
        label: "Email tone",
        help: "How should the outreach messages sound?",
        type: "select",
        options: sameOpts(["Friendly", "Professional", "Direct", "Casual", "Consultant-style"]),
        allowAI: true,
      },
      {
        id: "main_cta",
        label: "Main call to action",
        help: "What do you want the lead to do after reading your message?",
        type: "select",
        options: sameOpts(["Book a call", "Book a demo", "Get a quote", "Reply to email", "Visit website", "Free consultation"]),
        allowCustom: true,
      },
      {
        id: "follow_ups",
        label: "Follow-ups",
        help: "How many follow-up messages should we send if there's no reply?",
        type: "select",
        options: sameOpts(["No follow-up", "1 follow-up", "2 follow-ups", "3 follow-ups", "5 follow-ups"]),
        allowCustom: true,
      },
    ],
  },
];
